spring.application.name=nakliye
spring.mail.host=smtp.gmail.com
spring.mail.port=587
<<<<<<< HEAD
spring.mail.username=c.hasdalyazilim@gmail.com
spring.mail.password=mrhi tsci vebv dltp
=======
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
>>>>>>> 200cca3 (.env)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
